= `gf::AnyGrid` type
v0.1
include::bits/attributes.adoc[]
:toc: right

`AnyGrid` can contain any type of grid.

xref:core_grids.adoc[< Back to `core` Grids]

== Description

[source]
----
#include <gf2/core/AnyGrid.h>
class AnyGrid;
----

This class can be used when the type of grid can be used generically. It contains a link:https://en.cppreference.com/w/cpp/utility/variant[`std::variant`] of all the grid types of the library.

See also: xref:OrthogonalGrid.adoc[`OrthogonalGrid`],  xref:IsometricGrid.adoc[`IsometricGrid`], xref:StaggeredGrid.adoc[`StaggeredGrid`], xref:HexagonalGrid.adoc[`HexagonalGrid`]

== Static Member Functions

=== `make_hexagonal`

[source]
----
AnyGrid make_hexagonal(Vec2I layer_size, Vec2F tile_size, float side_length, CellAxis axis, CellIndex index); <1>
AnyGrid make_hexagonal(Vec2I layer_size, float radius, CellAxis axis, CellIndex index); <2>
----

<1> Create a generic hexagonal grid.
<2> Create a regular hexagonal grid.

=== `make_isometric`

[source]
----
AnyGrid make_isometric(Vec2I layer_size, Vec2F tile_size);
----

Create an isometric grid.

=== `make_orthogonal`

[source]
----
AnyGrid make_orthogonal(Vec2I layer_size, Vec2F tile_size);
----

Create an orthogonal grid.

=== `make_staggered`

[source]
----
AnyGrid make_staggered(Vec2I layer_size, Vec2F tile_size, CellAxis axis, CellIndex index);
----

Create a staggered grid.

== Member functions

=== `compute_bounds`

[source]
----
RectF compute_bounds() const;
----

Compute the local bounds of the grid.

=== `compute_cell_bounds`

[source]
----
RectF compute_cell_bounds(Vec2I position) const;
----

Compute the cell bounds at the given `position`.

=== `compute_contour`

[source]
----
std::vector<Vec2F> compute_contour(Vec2I position) const;
----

Compute a set of points that delimit the cell.

=== `compute_position`

[source]
----
Vec2I compute_position(Vec2F location) const;
----

Compute the position of a cell identified by its `location`.

=== `compute_neighbors`

[source]
----
std::vector<Vec2I> compute_neighbors(Vec2I position, Flags<CellNeighborQuery> flags = None) const;
----

Compute the position of the neighbors of a cell at the given `position`.

=== `compute_visible_area`

[source]
----
RectI compute_visible_area(RectF local) const;
----

Compute the visible area in terms of position.
