= `gf::BasicScene` type
v0.1
include::bits/attributes.adoc[]
:toc: right

A scene is responsible for handling the different steps of a game: process inputs, update the state, draw a frame.

xref:graphics_scenes.adoc[< Back to `graphics` Scenes]

== Description

[source]
----
#include <gf2/graphics/Scene.h>
class BasicScene;
----

In a game loop managed by a scene manager, the following methods are called in this order:

- <<process_event>> for all pending events
- <<handle_actions>> once all the events have been processed
- <<update>>
- <<render>>

A scene has a *clear color* used to clear the rendering surface at the beginning.

A scene has a *rank* determining its position in the stack of the scene manager (for scene managers that use a stack of scenes). It may be at the top of the stack, in the stack but not at the top or outside the stack.

A scene can be either *paused* or *resumed*. A paused scene is not updated. In other words, the update step is discarded. It is the user's responsability to pause or resume a scene. An scene is always resumed when becoming the top scene.

A scene can be either *hidden* or *shown*. A hidden scene is not rendererd. In other words, the render step is discarded. It is the user's responsability to hide or show a scene. An scene is always shown when becoming the top scene.

This class is not meant to be used directly, it serves as a base class for scenes with more features:

- xref:Scene.adoc[`gf::Scene`]

== Protected Types

[#scene_part]
=== `ScenePart`

[source]
----
struct ScenePart;
----

A part of a scene. A scene may be composed of several parts. This type is used by scenes for internal use.

.Data members for `gf::ScenePart`
[cols="1,1,2"]
|===
| Name | Type | Description

| `entities`
| xref:EntityContainer.adoc[`EntityContainer`]
| An entity container.

| `camera`
| xref:Camera.adoc[`Camera`]
| The camera used for the entities.
|===

See also: <<render_part>>

== Member Functions

=== `clear_color`

[source]
----
Color clear_color() const;
----

Get the clear color of the scene.

See also: <<set_clear_color>>

=== `handle_actions`

[source]
----
void handle_actions();
----

Call <<do_handle_actions>>.

=== `hidden`

[source]
----
bool hidden() const;
----

Tell if this scene is hidden.

See also: <<hide>>, <<show>>

=== `hide`

[source]
----
void hide();
----

Hide this scene, the scene is not rendered anymore. Call <<do_hide>>.

See also: <<show>>, <<hidden>>

=== `pause`

[source]
----
void pause();
----

Pause this scene, the scene is not updated anymore. Call <<do_pause>>.

See also: <<resume>>, <<paused>>

=== `paused`

[source]
----
bool paused() const;
----

Tell if the scene is paused.

See also: <<pause>>, <<resume>>

=== `process_event`

[source]
----
void process_event(const Event& event);
----

First call <<do_early_process_event>> and if it returns `false`, then call <<do_process_event>>.

=== `rank`

[source]
----
SceneRank rank() const;
----

Get the rank of the scene.

See also: <<set_rank>>

=== `resume`

[source]
----
void resume();
----

Resume this scene, the scene is updated again. Call <<do_resume>>.

See also: <<pause>>, <<paused>>

=== `render`

[source]
----
void render(RenderRecorder& recorder);
----

If the scene is not hidden, call <<do_render>>.

=== `set_clear_color`

[source]
----
void set_clear_color(Color color);
----

Set the clear color of the scene.

See also: <<clear_color>>

=== `set_rank`

[source]
----
void set_rank(SceneRank rank);
----

Set the rank of the scene. This function is called by the render manager when the user modifies the stack of scenes. If the new rank is different from the old rank, <<on_rank_change>> is called.

See also: <<rank>>, <<on_rank_change>>

=== `set_surface_size`

[source]
----
void set_surface_size(Vec2I size);
----

Set the rendering surface size. This function is called by the render manager when the surface changes its size.

See also: <<surface_size>>

=== `show`

[source]
----
void show();
----

Show this scene, the scene is rendered again. Call <<do_show>>.

See also: <<hide>>, <<hidden>>

=== `surface_size`

[source]
----
Vec2I surface_size() const;
----

Get the rendering surface size.

See also: <<set_surface_size>>

=== `update`

[source]
----
void update(Time time);
----

If the scene is not paused, call <<do_update>>

== Protected Member Functions

=== `render_part`

[source]
----
void render_part(RenderRecorder& recorder, ScenePart& part);
----

Record the objects in the scene part.

See also: <<scene_part>>

== Private Virtual Member Functions

=== `do_early_process_event`

[source]
----
virtual bool do_early_process_event(const Event& event);
----

This function is called when <<process_event>> is called. By default, do nothing and return false.

The return value indicates if the event should be processed further. This is useful for user interfaces that may actually handle an event and do not want the rest of the game to handle the event.

See also: <<do_process_event>>

=== `do_handle_actions`

[source]
----
virtual void do_handle_actions();
----

This function is called when <<handle_actions>> is called. By default, do nothing.

=== `do_hide`

[source]
----
virtual void do_hide();
----

This function is called when <<hide>> is called. By default, do nothing.

=== `do_pause`

[source]
----
virtual void do_pause();
----

This function is called when <<pause>> is called. By default, do nothing.

=== `do_process_event`

[source]
----
virtual void do_process_event(const Event& event);
----

This function is called when <<process_event>> is called. By default, do nothing.

See also: <<do_early_process_event>>

=== `do_render`

[source]
----
virtual void do_render(RenderRecorder& recorder);
----

This function is called when <<render>> is called. By default, do nothing.

=== `do_resume`

[source]
----
virtual void do_resume();
----

This function is called when <<resume>> is called. By default, do nothing.

=== `do_show`

[source]
----
virtual void do_show();
----

This function is called when <<show>> is called. By default, do nothing.

=== `do_update`

[source]
----
virtual void do_update(Time time);
----

This function is called when <<update>> is called. By default, do nothing.

=== `on_rank_change`

[source]
----
virtual void on_rank_change(SceneRank old_rank, SceneRank new_rank);
----

This function is called when the actual rank of the scene is modified.

See also: <<set_rank>>

