= `core` Color
v0.1
include::bits/attributes.adoc[]
:toc: right

The color component defines color-related constants, types and functions.

xref:reference.adoc[< Back to reference]

== Variables

[#azure]
=== `gf::Azure`

[source]
----
#include <gf2/Color.h>
constexpr Color Azure;
----

The azure predefined color.

[#black]
=== `gf::Black`

[source]
----
#include <gf2/Color.h>
constexpr Color Black;
----

The black predefined color.

[#blue]
=== `gf::Blue`

[source]
----
#include <gf2/Color.h>
constexpr Color Blue;
----

The blue predefined color.

[#chartreuse]
=== `gf::Chartreuse`

[source]
----
#include <gf2/Color.h>
constexpr Color Chartreuse;
----

The chartreuse predefined color.

[#cyan]
=== `gf::Cyan`

[source]
----
#include <gf2/Color.h>
constexpr Color Cyan;
----

The cyan predefined color.

[#gray0]
=== `gf::Gray`

[source]
----
#include <gf2/Color.h>
constexpr Color Gray;
----

The gray predefined color.

[#green]
=== `gf::Green`

[source]
----
#include <gf2/Color.h>
constexpr Color Green;
----

The green predefined color.

[#magenta]
=== `gf::Magenta`

[source]
----
#include <gf2/Color.h>
constexpr Color Magenta;
----

The magenta predefined color.

[#orange]
=== `gf::Orange`

[source]
----
#include <gf2/Color.h>
constexpr Color Orange;
----

The orange predefined color.

[#red]
=== `gf::Red`

[source]
----
#include <gf2/Color.h>
constexpr Color Red;
----

The red predefined color.

[#rose]
=== `gf::Rose`

[source]
----
#include <gf2/Color.h>
constexpr Color Rose;
----

The rose predefined color.

[#spring]
=== `gf::Spring`

[source]
----
#include <gf2/Color.h>
constexpr Color Spring;
----

The spring predefined color.

[#violet]
=== `gf::Violet`

[source]
----
#include <gf2/Color.h>
constexpr Color Violet;
----

The violet predefined color.

[#white]
=== `gf::White`

[source]
----
#include <gf2/Color.h>
constexpr Color White;
----

The white predefined color.

[#yellow]
=== `gf::Yellow`

[source]
----
#include <gf2/Color.h>
constexpr Color Yellow;
----

The yellow predefined color.

== Types

[#bitmap]
=== `gf::Bitmap`

[source]
----
#include <gf2/Bitmap.h>
class Bitmap;
----

A bitmap is a grayscale image with a single 8 bit channel. xref:Bitmap.adoc[*Read more...*]

[#color]
=== `gf::Color`

[source]
----
#include <gf2/Color.h>
struct Color;
----

A color in the link:https://en.wikipedia.org/wiki/RGB_color_model[RGB color model]. xref:Color.adoc[*Read more...*].

[#image]
=== `gf::Image`

[source]
----
#include <gf2/Image.h>
class Image;
----

`Image` represents a bidimensional array of pixels. xref:Image.adoc[*Read more...*]

[#pixel_format]
=== `gf::PixelFormat`

[source]
----
#include <gf2/Image.h>
enum class PixelFormat : uint8_t;
----

The pixel format of the raw input of an image.

.Enumerators for `gf::PixelFormat`
[cols="1,1"]
|===
| Value | Description

| `gf::PixelFormat::Rgba32`
| 32 bit color with 8 bit per channel

| `gf::PixelFormat::Rgb24`
| 24 bit color with 8 bit per channel
|===

See also: <<image>>

== Functions

[#darker]
=== `gf::darker`

[source]
----
#include <gf2/Color.h>
Color darker(Color color, float percent = 0.5f)
----

Compute a darker color.

This function takes a `color` and gives a darker color based on a percentage. If this `percent` is 0, the same color is returned. If this `percent` is 1, the black color is returned.

.Example for `gf::darker`
[source,indent=0]
----
include::snippets/core_color.cc[tag=darker]
----

[#gray1]
=== `gf::gray`

[source]
----
#include <gf2/Color.h>
constexpr Color gray(float value = 0.5f);
----

Compute a gray color with `value`.

[#lighter]
=== `gf::lighter`

[source]
----
#include <gf2/Color.h>
Color lighter(Color color, float percent = 0.5f);
----

Compute a lighter color.

This function takes a `color` and gives a lighter color based on a percentage. If this `percent` is 0, the same color is returned. If this `percent` is 1, the white color is returned.

.Example for `gf::lighter`
[source,indent=0]
----
include::snippets/core_color.cc[tag=lighter]
----

[#opaque]
=== `gf::opaque`

[source]
----
#include <gf2/Color.h>
constexpr Color opaque(float value = 0.5f);
----

Compute an opaque white with `value` as its opacity. If `value` is 0, then transparent white is returned. If `value` is 1, then opaque white is returned.

.Example for `gf::opaque`
[source,indent=0]
----
include::snippets/core_color.cc[tag=opaque]
----
