= `core` Container
v0.1
include::bits/attributes.adoc[]
:toc: right

The container component contains specialized containers in addition to the link:https://en.cppreference.com/w/cpp/container[standard containers].

xref:reference.adoc[< Back to reference]

== Types

[#array2D]
=== `gf::Array2D<T>`

[source]
----
#include <gf2/Array2D.h>
template<typename T>
class Array2D;
----

An `Array2D<T>` represents a two-dimension array, organized in row-major order. xref:Array2D.adoc[*Read more...*]

[#binary_heap]
=== `gf::BinaryHeap<T, Compare>`

[source]
----
#include <gf2/BinaryHeap.h>
template<typename T, typename Compare = std::less<T>>
class BinaryHeap;
----

A `BinaryHeap<T, Compare>` is a mutable link:https://en.wikipedia.org/wiki/Binary_heap[binary heap]. xref:BinaryHeap.adoc[*Read more...*]

[#index_range_type]
=== `gf::IndexRange`

[source]
----
#include <gf2/Range.h>
using IndexRange = Range<std::size_t>;
----

An `IndexRange` is a xref:Range.adoc[`Range<T>`] specialized for `std::size_t` indices.

See also: <<index_range_function>>

[#position_range_type]
=== `gf::PositionRange`

[source]
----
#include <gf2/Range.h>
using PositionRange = Range2D<int>;
----

A `PositionRange` is a xref:Range2D.adoc[`Range2D<T>`] specialized for `int` indices, used in xref:Array2D.adoc[`Array2D<T>`]

See also: <<position_range_function>>

[#range_type]
=== `gf::Range<T>`

[source]
----
#include <gf2/Range.h>
template<typename T>
struct Range;
----

A `Range<T>` represents a half-open range of values. xref:Range.adoc[*Read more...*]

See also: <<range_function>>

=== `gf::Range2D<T>`

[source]
----
#include <gf2/Range.h>
template<typename T>
struct Range2D;
----

A `Range2D<T>` represents a range accross a 2D area. xref:Range2D.adoc[*Read more...*]

[#span]
=== `gf::Span<T>`

[source]
----
#include <gf2/Span.h>
template<typename T>
class Span;
----

A span is a non-owning reference to a contiguous sequence of objects. xref:Span.adoc[*Read more...*]

See also: <<static_span>>

[#static_span]
=== `gf::StaticSpan<T>`

[source]
----
#include <gf2/Span.h>
template<typename T, std::size_t N>
class StaticSpan;
----

A static span is a non-owning reference to a contiguous sequence of objects whose number is known at compile-time. xref:StaticSpan.adoc[*Read more...*]

See also: <<span>>

== Functions

[#index_range_function]
=== `gf::index_range`

[source]
----
#include <gf2/Range.h>
constexpr IndexRange index_range(std::size_t size);
----

Create an `IndexRange` for a container of size `size`.

See also: <<index_range_type>>

[#position_range_function]
=== `gf::position_range`

[source]
----
#include <gf2/Range.h>
constexpr PositionRange position_range(Vec2I size);
----

Create a `PositionRange` for a 2D area of size `size`.

See also: <<position_range_type>>

[#range_function]
=== `gf::range`

[source]
----
#include <gf2/Range.h>
template<typename T>
constexpr Range<T> range(T lo, T hi);
----

Create a range between `lo` (included) and `hi` (excluded).

See also: <<range_type>>
