= `core` Serialization
v0.1
include::bits/attributes.adoc[]
:toc: right

The serialization component gives classes to serialize and deserialize a wide range of types.

link:https://en.wikipedia.org/wiki/Serialization[Serialization] is an important process that can be used in gamedev for resources, saves or network messages.

An *archive* is a piece of serialized data. It can be handled by any xref:core_streams.adoc[streams]. The transformation between in-memory data and an archive is achieved with a serializer and a deserializer.

An archive has a header with two fields: a magic constant of 16 bits (the two characters `'g'` and `'f'`) and a version integer of 16 bits encoded in big endian. Then data is serialized as specified by the serialization operators. Basic types are handled directly by the serializer and deserializer through direct methods. Complex types are handled by <<operator_pipe>>.

User defined types may easily be serialized and deserialized with a generic function taking an archive as a template argument.

.Example for serialization of user-defined types
[source,indent=0]
----
include::snippets/core_serialization.cc[tag=user_defined]
----

The version of the archive may be used to handle the evolution of the archive data in a transparent way.

.Example for the use of version
[source,indent=0]
----
include::snippets/core_serialization.cc[tag=version]
----

xref:reference.adoc[< Back to reference]

== Types

[#deserializer]
=== `gf::Deserializer`

[source]
----
#include <gf2/Serialization.h>
class Deserializer;
----

`Deserializer` is responsible for deserializing basic types. xref:Deserializer.adoc[*Read more...*]

[#serializer]
=== `gf::Serializer`

[source]
----
#include <gf2/Serialization.h>
class Serializer;
----

`Serializer` is responsible for serializing basic types. xref:Serializer.adoc[*Read more...*]


== Operators

[#operator_pipe]
=== `operator|`

[source,subs="verbatim,quotes"]
----
#include <gf2/SerializationOps.h>
Serializer& operator|(Serializer& ar, const _Type_& value);
Deerializer& operator|(Deserializer& ar, _Type_& value);
----

This operator is defined for `Serializer` and `Deserializer` so that it can be made generic to define both serialization and deserialization with a single definition. The library defines this operator for the following types:

- basic types: `bool`, `char`, `double`, `float`, `int8_t`, `int16_t`, `int32_t`, `int64_t`, `uint8_t`, `uint16_t`, `uint32_t`, `uint64_t` , in addition to link:https://en.cppreference.com/w/cpp/language/array[array] and link:https://en.cppreference.com/w/cpp/language/enum[enum]
- standard types: `std::array`, `std::map`, `std::pair`, `std::optional`, `std::set`, `std::string`, `std::tuple`, `std::unorderer_map`, `std::unordered_set`, `std::variant`, `std::vector`
- gf2 types: xref:Array2D.adoc[`Array2D<T>`], xref:Circ.adoc[`Circ<T>`], xref:Color.adoc[`Color`], xref:Flags.adoc[`Flags<E>`], xref:Rect.adoc[`Rect<T>`], xref:Time.adoc[`Time`], xref:Vec2.adoc[`Vec2<T>`], xref:Vec3.adoc[`Vec3<T>`]

