= `core` Container
v0.1
:toc: right
:toclevels: 3
:homepage: https://gamedevframework.github.io/
:stem: latexmath
:source-highlighter: rouge
:source-language: c++
:rouge-style: thankful_eyes
:sectanchors:
:xrefstyle: full
:nofooter:
:docinfo: shared-head
:icons: font

The container component contains specialized containers in addition to the link:https://en.cppreference.com/w/cpp/container[standard containers].

xref:reference.adoc[< Back to reference]

== Types

[#_array2D]
=== `gf::Array2D<T>`

[source]
----
#include <gf/Array2D.h>
template<typename T>
class Array;
----

An `Array2D<T>` represents a two-dimension array, organized in row-major order. xref:Array2D.adoc[*Read more...*]

[#_index_range_type]
=== `gf::IndexRange`

[source]
----
#include <gf/Range.h>
using IndexRange = Range<std::size_t>;
----

An `IndexRange` is a xref:Range.adoc[`Range<T>`] specialized for `std::size_t` indices.

See also: <<_index_range_function>>

[#_position_range_type]
=== `gf::PositionRange`

[source]
----
#include <gf/Range.h>
using PositionRange = Range2D<int>;
----

A `PositionRange` is a xref:Range2D.adoc[`Range2D<T>`] specialized for `int` indices, used in xref:Array2D.adoc[`Array2D<T>`]

See also: <<_position_range_function>>

[#_range_type]
=== `gf::Range<T>`

[source]
----
#include <gf/Range.h>
template<typename T>
struct Range;
----

A `Range<T>` represents a half-open range of values. xref:Range.adoc[*Read more...*]

See also: <<_range_function>>

=== `gf::Range2D<T>`

[source]
----
#include <gf/Range.h>
template<typename T>
struct Range2D;
----

A `Range2D<T>` represents a range accross a 2D area. xref:Range2D.adoc[*Read more...*]

== Functions

[#_index_range_function]
=== `gf::index_range`

[source]
----
#include <gf/Range.h>
constexpr IndexRange index_range(std::size_t size);
----

Create an `IndexRange` for a container of size `size`.

See also: <<_index_range_type>>

[#_position_range_function]
=== `gf::position_range`

[source]
----
#include <gf/Range.h>
constexpr PositionRange position_range(Vec2I size);
----

Create a `PositionRange` for a 2D area of size `size`.

See also: <<_position_range_type>>

[#_range_function]
=== `gf::range`

[source]
----
template<typename T>
constexpr Range<T> range(T lo, T hi);
----

Create a range between `lo` (included) and `hi` (excluded).

See also: <<_range_type>>
