= `core` Grids
v0.1
include::bits/attributes.adoc[]
:toc: right

The grids component provides the classes for handling maps organized in grids.

A grid is a set of cells with a specific organization. As a grid is a two-dimensional object, the cells of a grid can be identified with two coordinates. Some kind of grids have several variants according to the layout of the grid. The library supports the following types of grid:

- Orthogonal grids (rectangle cells organised in a rectangle)
- Isometric grids (rhombus cells organised in a rhombus)
- Staggered grids (rhombus cells organised in a rectangle)
- Hexagonal grids (hexagon cells organised in a rectangle)

xref:reference.adoc#core[< Back to reference]

See also: xref:article_grids_howto.adoc[`Grids How To`]

== Types

[#any_grid]
=== `gf::AnyGrid`

[source]
----
#include <gf2/core/AnyGrid.h>
class AnyGrid;
----

`AnyGrid` can contain any type of grid. xref:AnyGrid.adoc[*Read more...*]

See also: <<hexagonal_grid>>, <<isometric_grid>>, <<orthogonal_grid>>, <<staggered_grid>>


[#cells_axis]
=== `gf::CellAxis`

[source]
----
#include <gf2/core/GridTypes.h>
enum class CellAxis : uint8_t;
----

The axis that is shifted in staggered and hexagonal maps.

.Enumerators for `gf::CellAxis`
[cols="2,3"]
|===
| Value | Description

| `gf::CellAxis::X`
| The x-axis is shifted

| `gf::CellAxis::Y`
| The y-axis is shifted
|===


[#cell_flip]
=== `gf::CellFlip`

[source]
----
#include <gf2/core/GridTypes.h>
enum class CellFlip : uint8_t;
----

The way a cell may be flipped. `CellFlip` can be used with xref:Flags.adoc[`Flags<E>`].

.Enumerators for `gf::CellFlip`
[cols="2,3"]
|===
| Value | Description

| `gf::CellFlip::Horizontally`
| The cell is flipped horizontally

| `gf::CellFlip::Vertically`
| The cell is flipped vertically

| `gf::CellFlip::Diagonally`
| The cell is flipped diagonally

| `gf::CellFlip::Rotation60`
| The cell is rotated by 60°

| `gf::CellFlip::Rotation120`
| The cell is rotated by 120°
|===

[#cells_index]
=== `gf::CellIndex`

[source]
----
#include <gf2/core/GridTypes.h>
enum class CellIndex : uint8_t;
----

The indices that are shifted along the shifted axis.

.Enumerators for `gf::CellIndex`
[cols="2,3"]
|===
| Value | Description

| `gf::CellIndex::Odd`
| The odd indices are shifted.

| `gf::CellIndex::Even`
| The even indices are shifted.
|===


[#cells_neighbor_query]
=== `gf::CellNeighborQuery`

[source]
----
#include <gf2/core/Cells.h>
enum class CellNeighborQuery : uint8_t;
----

The specification of the query when asking for neighborhood. `CellNeighborQuery` can be used with xref:Flags.adoc[`Flags<E>`].

.Enumerators for `gf::CellNeighborQuery`
[cols="2,3"]
|===
| Value | Description

| `gf::CellNeighborQuery::Valid`
| The neighbors must be valid cells.

| `gf::CellNeighborQuery::Diagonal`
| The neighbors may be in diagonal.
|===


[#grid_orientation]
=== `gf::GridOrientation`

[source]
----
#include <gf2/core/GridTypes.h>
enum class GridOrientation : uint8_t;
----

The orientation of the grid.

.Enumerators for `gf::GridOrientation`
[cols="2,3"]
|===

| `gf::GridOrientation::Unknown`
| Unknown orientation

| `gf::GridOrientation::Orthogonal`
| Orthogonal orientation

| `gf::GridOrientation::Isometric`
| Isometric orientation

| `gf::GridOrientation::Staggered`
| Staggered orientation

| `gf::GridOrientation::Hexagonal`
| Hexagonal orientation
|===


[#hexagonal_grid]
=== `gf::HexagonalGrid`

[source]
----
#include <gf2/core/Grids.h>
class HexagonalGrid;
----

An hexagonal grid is a grid with hexagonal cells organized in a rectangle. xref:HexagonalGrid.adoc[*Read more...*]

[#isometric_grid]
=== `gf::IsometricGrid`

[source]
----
#include <gf2/core/Grids.h>
class IsometricGrid;
----

An isometric grid is a grid with rhombus cells organized in a rhombus. xref:IsometricGrid.adoc[*Read more...*]

[#orthogonal_grid]
=== `gf::OrthogonalGrid`

[source]
----
#include <gf2/core/Grids.h>
class OrthogonalGrid;
----

An orthogonal grid is a grid with rectangle cells organized in a rectangle. xref:OrthogonalGrid.adoc[*Read more...*]

[#staggered_grid]
=== `gf::StaggeredGrid`

[source]
----
#include <gf2/core/Grids.h>
class StaggeredGrid;
----

A staggered grid is a grid with rhombus cells organized in a rectangle. xref:StaggeredGrid.adoc[*Read more...*]
