= `gf::GridCells` type
v0.1
include::bits/attributes.adoc[]
:toc: right

`GridCells` can contain any type of cells.

xref:core_grids.adoc[< Back to `core` Grids]

== Description

[source]
----
#include <gf2/Cells.h>
class GridCells;
----

This class can be used when the type of cells can be used generically. It contains a link:https://en.cppreference.com/w/cpp/utility/variant[`std::variant`] of all the cells of the library.

See also: xref:OrthogonalCells.adoc[`OrthogonalCells`], xref:StaggeredCells.adoc[`StaggeredCells`], xref:HexagonalCells.adoc[`HexagonalCells`]

== Static Member Functions

=== `make_hexagonal`

[source]
----
GridCells make_hexagonal(Vec2F tile_size, float side_length, CellAxis axis, CellIndex index); <1>
GridCells make_hexagonal(float radius, CellAxis axis, CellIndex index); <2>
----

<1> Create generic hexagonal cells.
<2> Create regular hexagonal cells.

=== `make_orthogonal`

[source]
----
GridCells make_orthogonal(Vec2F tile_size);
----

Create orthogonal cells.

=== `make_staggered`

[source]
----
GridCells make_staggered(Vec2F tile_size, CellAxis axis, CellIndex index);
----

Create staggered cells.

== Member functions

=== `compute_bounds`

[source]
----
RectF compute_bounds(Vec2I layer_size) const;
----

Compute the local bounds of the cells, with a layer of size `layer_size`.

=== `compute_cell_bounds`

[source]
----
RectF compute_cell_bounds(Vec2I coordinates) const;
----

Compute the cell bounds at the given `coordinates`.

=== `compute_contour`

[source]
----
std::vector<Vec2F> compute_contour(Vec2I coordinates) const;
----

Compute a set of points that delimit the cell.

=== `compute_coordinates`

[source]
----
Vec2I compute_coordinates(Vec2F position) const;
----

Compute the coordinates of a cell identified by its `position`.

=== `compute_neighbors`

[source]
----
std::vector<Vec2I> compute_neighbors(Vec2I coordinates, Vec2I layer_size, Flags<CellNeighborQuery> flags = None) const;
----

Compute the coordinates of the neighbors of a cell at the given `coordinates`.

=== `compute_visible_area`

[source]
----
RectI compute_visible_area(RectF local) const;
----

Compute the visible area in terms of coordinates.
