= `gf::Span<T>` type
v0.1
include::bits/attributes.adoc[]
:toc: right

A span is a non-owning reference to a contiguous sequence of objects.

xref:core_container.adoc[< Back to `core` Container]

== Description

[source]
----
#include <gf/core/Span.h>
template<typename T>
class Span;
----

This class stores a pointer to some data and its size. It can be built from various inputs: `std::vector`, static array, pointer and size.

See also: xref:StaticSpan.adoc[`StaticSpan<T>`]

== Member functions

=== `Span<T>` constructors

[source]
----
constexpr Span() noexcept; <1>
constexpr Span(std::nullptr_t) noexcept; <2>
constexpr Span(T* data, std::size_t size) noexcept; <3>
template<typename U>
constexpr Span(U (&data)[N]) noexcept; <4>
template<typename U>
constexpr Span(std::vector<U>& array) noexcept; <5>
template<typename U>
constexpr Span(const std::vector<U>& array) noexcept; <6>
template<typename U>
constexpr Span(std::array<U, N>& array) noexcept; <7>
template<typename U>
constexpr Span(Span<U, N> other) noexcept; <8>
template<typename U>
constexpr Span(StaticSpan<U, N> other) noexcept; <9>
----

<1> Default constructor, `data` is `nullptr`.
<2> Null constructor, `data` is `nullptr`.
<3> Constructor from a pointer and a size.
<4> Constructor from a static array.
<5> Constructor from a `std::vector`.
<6> Constructor from a `const std::vector`.
<7> Constructor from a `std::array`.
<8> Constructor from another span.
<9> Constructor from a static span.

=== `begin`

[source]
----
constexpr const T* begin() const noexcept; <1>
constexpr T* begin() noexcept; <2>
----

<1> Get an iterator to the first element of the span.
<2> Same but the iterator is not `const`.

See also: <<end>>

=== `data`

[source]
----
constexpr const T* data() const noexcept; <1>
constexpr T* data() noexcept; <2>
----

<1> Get a pointer to the elements.
<2> Same but the elements can be modified.

=== `empty`

[source]
----
constexpr bool empty() const noexcept;
----

Check is the span is empty.

=== `end`

[source]
----
constexpr const T* end() const noexcept; <1>
constexpr T* end() noexcept; <2>
----

<1> Get an iterator past the last element of the span.
<2> Same but the iterator is not `const`.

See also: <<begin>>

=== `first`

[source]
----
constexpr Span<T> first(std::size_t count) const noexcept; <1>
template<std::size_t C>
constexpr StaticSpan<T, C> first() const noexcept; <2>
----

<1> Take a runtime span on the first `count` elements.
<2> Take a compile-time span on the first `C` elements.

=== `first_except`

[source]
----
constexpr Span<T> first_except(std::size_t count) const noexcept; <1>
template<std::size_t C>
constexpr Span<T> first_except() const noexcept; <2>
----

<1> Take a runtime span on the first elements except the `count` last.
<2> Take a compile-time span on the first elements except the `C` last.

=== `get`

[source]
----
template<std::size_t I>
constexpr const T& get() const noexcept; <1>
template<std::size_t I>
constexpr T& get() noexcept; <2>
----

<1> Get an element at a constant index.
<2> Same but the element can be modified.

=== `last`

[source]
----
constexpr Span<T> last(std::size_t count) const noexcept; <1>
template<std::size_t C>
constexpr StaticSpan<T, C> last() const noexcept; <2>
----

<1> Take a runtime span on the last `count` elements.
<2> Take a compile-time span on the last `C` elements.

=== `last_except`

[source]
----
constexpr Span<T> last_except(std::size_t count) const noexcept; <1>
template<std::size_t C>
constexpr Span<T> last_except() const noexcept; <2>
----

<1> Take a runtime span on the last elements except the `count` first.
<2> Take a compile-time span on the last elements except the `C` first.

=== `size`

[source]
----
constexpr std::size_t size() const noexcept;
----

Get the number of elements in the span.

=== `slice`

[source]
----
constexpr Span<T> slice(std::size_t b, std::size_t e) const noexcept; <1>
template<std::size_t B, std::size_t E>
constexpr StaticSpan<T, E - B> slice() const noexcept; <2>
----

<1> Take a runtime sub-span between `b` (included) and `e` (not included).
<2> Take a compile-time sub-span between `B` (included) and `E` (not included).

== Operators

=== `operator[]`

[source]
----
constexpr const T& operator[](std::size_t index) const noexcept; <1>
constexpr T& operator[](std::size_t index) noexcept; <2>
----

<1> Get the element at a given index.
<2> Same but the element can be modified.
