name: Ubuntu build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        mode: [ asan, debug, release ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout gf2
        uses: actions/checkout@v3
        with:
          repository: GamedevFramework/gf2
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libboost-all-dev vulkan-validationlayers-dev

      - name: Configure xmake environment
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake" >> $GITHUB_ENV

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: 'ubuntu'

      - name: Update xmake repository
        run: xmake repo --update

      - name: Retrieve dependencies hash
        id: deps_hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" >> $GITHUB_OUTPUT

      - name: Retrieve cached dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ubuntu-${{ matrix.mode }}-${{ steps.deps_hash.outputs.hash }}

      - name: Install gf2 dependencies
        run: xmake config --mode=${{ matrix.mode }} --yes

      - name: Build gf2
        run: xmake --yes

      - name: Test gf2
        run: |
          xmake run gf2_core_tests
          xmake run gf2_network_tests
          xmake run gf2_audio_tests
