name: UbuntuBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libfmt-dev libboost-dev libfreetype6-dev zlib1g-dev libpugixml-dev libvulkan-dev vulkan-validationlayers-dev

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: actions/checkout@v3
        with:
          repository: GamedevFramework/gf2
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Configure gf
        run: cmake -DCMAKE_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -S ${{ github.workspace }} -B ${{ github.workspace }}/build

      - name: Build gf
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C ${{ env.BUILD_TYPE }} -T test --output-on-failure
